Src/ff.Web/Controllers/CarKindController.cs
using Microsoft.AspNetCore.Mvc;

namespace ff.Web.Controllers
{
    public class CarKindController : Controller
    {
        private readonly ILogger<CarKindController> _logger;

        public CarKindController(ILogger<CarKindController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Go To CarKind ...");
            return View();
        }
    }
}

Src/ff.Web/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

namespace ff.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ILogger<CustomerController> _logger;

        public CustomerController(ILogger<CustomerController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Go To Customer ...");
            return View();
        }
    }
}

Src/ff.Web/Controllers/ItemMainController.cs
using Microsoft.AspNetCore.Mvc;

namespace ff.Web.Controllers
{
    public class ItemMainController : Controller
    {
        private readonly ILogger<ItemMainController> _logger;

        public ItemMainController(ILogger<ItemMainController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Go To ItemMain ...");
            return View();
        }
    }
}

Src/ff.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;

namespace ff.Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly ILogger<OrderController> _logger;

        public OrderController(ILogger<OrderController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            _logger.LogInformation("Go To Order ...");
            return View();
        }

        public IActionResult Create()
        {
            _logger.LogInformation("Go To Order Create ...");
            return View();
        }
    }
}

Src/ff.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/css/admin/fonts-all.css">
    <link rel="stylesheet" href="~/css/admin/icon-all.css">
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/admin/nucleo-icons.css">
    <link rel="stylesheet" href="~/css/admin/black-dashboard.css">
    <link rel="stylesheet" href="~/css/sweetalert/sweetalert-dark.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <link rel="shortcut icon" href="~/img/favicon.ico" asp-append-version="true">
    <title>@ViewData["Title"] - Foreteller</title>
</head>

<body class="">
    <div class="wrapper">
        <div class="sidebar">
            <div class="sidebar-wrapper" fragment="sidebar">
                <div class="logo">
                    <a class="simple-text logo-normal" asp-controller="Home" asp-action="Index">
                        <img src="~/img/Logo.png" alt="Catcher" style="opacity: .8;max-width: 30%;">
                        <span>foreteller</span>
                    </a>
                </div>
                <ul class="nav">
                     <li>
                        <a href="#dataSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">資料維護 <i class="tim-icons icon-minimal-down"></i></a>
                         <ul class="collapse list-unstyled" id="dataSubmenu">
                              <li>
                                  <a asp-controller="CarKind" asp-action="Index">
                                    <i class="tim-icons icon-delivery-fast"></i>
                                    <p>車種資料維護</p>
                                  </a>
                                  <a asp-controller="ItemMain" asp-action="Index">
                                    <i class="tim-icons icon-settings"></i>
                                     <p>零件資料維護</p>
                                  </a>
                                  <a asp-controller="Customer" asp-action="Index">
                                    <i class="tim-icons icon-badge"></i>
                                    <p>客戶資料維護</p>
                                  </a>
                              </li>
                         </ul>
                     </li>
                    <li>
                        <a href="#orderSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">訂單功能 <i class="tim-icons icon-minimal-down"></i></a>
                        <ul class="collapse list-unstyled " id="orderSubmenu">
                            <li>
                                 <a asp-controller="Order" asp-action="Create">
                                     <i class="tim-icons icon-cart"></i>
                                     <p>新增訂單</p>
                                 </a>
                                 <a asp-controller="Order" asp-action="Index">
                                     <i class="tim-icons icon-notes"></i>
                                     <p>訂單查詢</p>
                                 </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <div class="navbar-toggle d-inline">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#">foreteller</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                        <span class="navbar-toggler-bar navbar-kebab"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navigation">
                        <ul class="navbar-nav ml-auto">
                            <li class="search-bar input-group">
                                <button class="btn btn-link" id="search-button" data-toggle="modal"
                                    data-target="#searchModal"><i class="tim-icons icon-zoom-split"></i>
                                    <span class="d-lg-none d-md-block">Search</span>
                                </button>
                            </li>
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <div class="notification d-none d-lg-block d-xl-block"></div>
                                    <i class="tim-icons icon-email-85"></i>
                                    <p class="d-lg-none">
                                        Notifications
                                    </p>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded
                                            to your email</a></li>
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">You
                                            have 5 more tasks</a></li>
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Your friend Michael
                                            is in town</a></li>
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Another
                                            notification</a></li>
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Another one</a></li>
                                </ul>
                            </li>
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <i class="tim-icons icon-single-02"></i>
                                    <p class="d-lg-none">
                                        Setting
                                    </p>
                                </a>
                                <ul class="dropdown-menu dropdown-navbar">
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Profile</a></li>
                                    <li class="nav-link"><a href="#" class="nav-item dropdown-item">Settings</a></li>
                                    <li class="dropdown-divider"></li>
                                    <li class="nav-link"><a class="nav-item dropdown-item" asp-controller="Account" asp-action="Login">Log
                                            in</a></li>
                                </ul>
                            </li>
                            <li class="separator d-lg-none"></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog"
                aria-labelledby="searchModal" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <i class="tim-icons icon-simple-remove"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Navbar -->
            <div class="content">
                @RenderBody()
            </div>
            <footer class="footer">
                <div class="container-fluid" th:fragment="footer">
                    <ul class="nav">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                About Me
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                Q&A
                            </a>
                        </li>
                    </ul>
                    <div class="copyright">
                        ©
                        <script>
                            document.write(new Date().getFullYear())
                        </script> made with <i class="tim-icons icon-heart-2"></i> by
                        <a href="#" target="_blank">No Name</a> for a better tool.
                    </div>
                </div>
            </footer>
        </div>
    </div>

     <script type="text/javascript">
        window.root = "@Url.Content("~/")";
    </script>
<!-- Core -->
    <script src="~/js/admin/core/jquery.min.js"></script>
    <script src="~/js/admin/core/popper.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap.min.js"></script>
    <script src="~/js/admin/plugins/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/js/admin/plugins/bootstrap-notify.js"></script>
    <script src="~/lib/sweetalert/sweetalert.min.js"></script>
    <script src="~/js/admin/plugins/chartjs.min.js"></script>

    <!-- Theme JS -->
    <script src="~/js/admin/black-dashboard.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/_layout.js"></script>

    <!-- axios -->
    <script src="~/js/cookie.js"></script>
    <script src="~/js/axios/axios.min.js"></script>
    <script src="~/js/utils/axiosPlugin.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Src/ff.Web/Views/Shared/_Layout_Indentity.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/css/admin/fonts-all.css">
    <link rel="stylesheet" href="~/css/admin/icon-all.css">
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/admin/nucleo-icons.css">
    <link rel="stylesheet" href="~/css/admin/black-dashboard.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    <link rel="shortcut icon" href="~/img/favicon.ico" asp-append-version="true">
    <title>@ViewData["Title"] - Catcher.Web</title>
</head>
<body class="">
   @RenderBody()

    <script type="text/javascript">
        window.root = "@Url.Content("~/")";
    </script>
<!-- Core -->
    <script src="~/js/admin/core/jquery.min.js"></script>
    <script src="~/js/admin/core/popper.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap.min.js"></script>
    <script src="~/lib/underscore/underscore.js"></script>
    <script src="~/js/admin/plugins/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/js/admin/plugins/bootstrap-notify.js"></script>

    <!-- Theme JS -->
    <script src="~/js/admin/black-dashboard.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/js/_layout.js"></script>

    <!-- axios -->
    <script src="~/js/cookie.js"></script>
    <script src="~/js/axios/axios.min.js"></script>
    <script src="~/js/utils/axiosPlugin.js"></script>
    <script src="~/js/api/loginAapi.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>